PR_TEMPLATE_ADDED
kubesimplify/tweets pull request #14
Opened 2022-04-02 08:00 UTC by vish-han

the PR TEMPLATE has been added in the .github directory . @anubha-v-ardhan please review the code and let me know if you want some changes.

2022-04-02 13:15 UTC, anubha-v-ardhan requested changes
Folks will be making pull requests for tweets (temporary plan untill we make issue based workflow), so I think, we need the template related to that.

2022-04-02 13:17 UTC, vish-han commented
Can u suggest what changes I should make?

2022-04-05 18:26 UTC, anubha-v-ardhan requested changes

2022-04-05 18:26 UTC, anubha-v-ardhan commented on .github/PULL_REQUEST_TEMPLATE/pull_request_template.md
> +
We should add something like "New Tweet (Adding a new `*.tweet` file to tweet from KubeSimplify's Twitter" as currently we only have PR based way of tweeting

2022-04-05 18:41 UTC, vish-han commented on .github/PULL_REQUEST_TEMPLATE/pull_request_template.md
> +
Ok working on it.👍

2022-04-17 11:15 UTC, saiyam1814 commented on .github/PULL_REQUEST_TEMPLATE/pull_request_template.md
> +
@vish-han you are done with your changes?

2022-04-17 13:06 UTC, vish-han commented on .github/PULL_REQUEST_TEMPLATE/pull_request_template.md
> +
Some changes are required bhia, working on it .

2022-04-23 05:58 UTC, saiyam1814 commented
@anubha-v-ardhan we don't need a PR template as PR will be created from the issue itself. right ?

2022-04-23 06:10 UTC, anubha-v-ardhan commented
> @anubha-v-ardhan we don't need a PR template as PR will be created from the issue itself. right ?

Yeah, This was a temporary plan when we only had "PR to tweet" support. I think we can close this now

2022-04-23 06:31 UTC, closed without merging